defaults:
  - _self_
  - bot:
      - bot:
        - logging
  - mlflow: 
      - mlflow
  - dataset:
      - dataset
      - preprocessing
      - paths
  - model:
      - model
      - freezing
      - optimizer
  - train:
      - train
  - exports:
      - exports