defaults:
  - _self_
  - bot:
      - bot
  - mlflow: 
      - mlflow
  - dataset:
      - dataset
      - preprocessing
      - paths
  - model:
      - model
      - freezing
      - optimizer
  - train:
      - train