mlflow:
  enabled: True
  tracking_uri: "http://localhost:5000"
  experiment_name: dog-breed
  run_name: "vit-l-16-run"
  logging:
    metrics: true
    params: true
    plots: true
    models: true
  artifacts:
    save_checkpoints: true
    save_samples: true