train:
  epochs: 7
  batch_size: 8
  valid_batch_size: 32
  learning_rate: 0.009
  momentum: 0.9
  device: "auto"
  log_interval: 100
  visualize_samples: True
  shuffle: true
  num_workers: 4
  plot_interval: 1
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  precision: "16-mixed"
  deterministic: True